os:
  - linux

addons:
  apt:
    packages:
      # For latex rendering in matplotlib
      - dvipng
      - ghostscript
      - latex-mk

  homebrew:
    packages:
      # For latex rendering in matplotlib
      - dvipng
      - ghostscript
    casks:
      - mactex

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# Python for Mac is not yet officially supported by Travis.
# We test only 2.7 and 3.6 on macOS for now.
matrix:
  include:
    - os: osx
      language: generic
      env: PYTHON=2.7.10
    - os: osx
      language: generic
      env: PYTHON=3.6.0

before_install:
  - bash .ci/mac-os_before_install.sh

install:
  - |
    source .ci/set_pip_name.sh;
    ${pip} install . --upgrade;

before_script:
  - |
    # no X server in TravisCI
    export MPLBACKEND=Agg;
    export PATH="$PATH:/usr/bin/latex"
    whereis latex
    evo_config set plot_backend Agg;

script:
  - |
    ${pip} install pytest --upgrade;
    pytest -sv;

notifications:
  slack: spark-lab-mit:gTc6ivvZ6ZoNtbxcrk1YzRsc
